name: Build and Release
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: 
          - ubuntu
          - windows
          - macos
        arch:
          - amd64
          - arm64

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Tailwind CLI
        shell: bash
        run: |
          npm install @tailwindcss/cli
          echo "${{ github.workspace }}/node_modules/.bin" >> $GITHUB_PATH

      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.arch }}" != "" ]; then
            export GOARCH=${{ matrix.arch }}
          fi
          go generate ./...
          go build -v -o receivefiles.bin .

      - name: Test
        run: go test -v ./...

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_${{ matrix.arch }}
          path: receivefiles.bin
          retention-days: 1


  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./build

      - name: Compress files
        shell: bash
        run: |
          tree build
          mkdir -p release
          appname="receivefiles"
          for dirpath in ./build/*; do
            dir=$(basename "$dirpath")
            bin="$dir/$appname.bin"
            if [[ "$dir" == *windows* ]]; then
              out_name="$appname_$dir.zip" 
              mv "$bin" "$dir/$appname.exe"
              (cd "$dir" && zip "../../release/$out_name" "$appname.exe")
            else
              out_name="$appname_$dir.tar.gz"
              mv "$bin" "$dir/$appname"
              (cd "$dir" && tar -czf "../../release/$out_name" "$appname")
            fi
            echo "Created: release/$out_name"
          done
          tree release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*